//--------------------Allgemein---------------------------
#define MAIN_OpenKnxId 0xAE
#define MAIN_ApplicationNumber 0x00
#define MAIN_ApplicationVersion 0x06
#define MAIN_OrderNumber "TD-12-mD-S" //may not work with multiple devices on same hardware or app on different hardware
/*  Dummy modul:
    has to be filled with ETS parameter and GrpObjects
    generated by Kaenx-Creator or similar tools
*/